"""add sources and extractions tables

Revision ID: c4d382af8494
Revises: 
Create Date: 2026-08-11 20:23:03.882251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4d382af8494'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.Enum('document', 'message', 'text_paste', name='source_type_enum'), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='source_status_enum'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_status', 'sources', ['status'], unique=False)
    op.create_index('idx_source_type', 'sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_sources_filename'), 'sources', ['filename'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_table('extractions',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0', nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extraction_entity', 'extractions', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_extraction_source', 'extractions', ['source_id'], unique=False)
    op.create_index(op.f('ix_extractions_id'), 'extractions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extractions_id'), table_name='extractions')
    op.drop_index('idx_extraction_source', table_name='extractions')
    op.drop_index('idx_extraction_entity', table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_filename'), table_name='sources')
    op.drop_index('idx_source_type', table_name='sources')
    op.drop_index('idx_source_status', table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
